language: generic
sudo: required
services:
  - docker
before_install:
  - docker build -t bluealoha/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true bluealoha/react-test npm test

after_success:
  - docker build -t bluealoha/multi-client ./client
  - docker build -t bluealoha/multi-nginx ./nginx
  - docker build -t bluealoha/multi-server ./server
  - docker build -t bluealoha/multi-worker ./worker
  # Log in docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # Push the images to docker hub
  - docker push bluealoha/multi-client
  - docker push bluealoha/multi-nginx
  - docker push bluealoha/multi-server
  - docker push bluealoha/multi-worker

# Deploy the docker image to AWS Elastic Beanstalk
deploy:
  provider: elasticbeanstalk
  region: "us-east-2"
  app: "multi-docker"
  env: "MultiDocker-env"
  bucket_name: "elasticbeanstalk-us-east-2-837527317628"
  bucket_path: "docker-multi"
  on:
    branch: master
  access_key_id:
    secure: "$AWS_ACCESS_KEY"
  secret_access_key:
    secure: "$AWS_SECRET_KEY"